name: "Terraform"

on:
  push:
    branches:
      - main
 
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://sample-cluster-public-vault-0a2cacb2.cee53a21.z1.hashicorp.cloud:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              secret/data/aws aws_access_key_id | AWS_ACCESS_KEY_ID ;
              secret/data/aws aws_secret_access_key | AWS_SECRET_ACCESS_KEY ;

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: cd iac && terraform fmt -check

      - name: Terraform Init
        id: init
        run: cd iac && terraform init
      
      - name: Terraform Validate
        id: validate
        run: cd iac && terraform validate -no-color

      #- name: Terraform Plan
      #  id: plan
      #  run: cd iac && terraform plan -no-color -input=false -out=execution-plan.binary && terraform show --json execution-plan.binary > execution-plan.json
      #  env:
      #    AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 